git clone https://git.drupal.org/project/adm.git
git clone https://git.drupal.org/project/agov.git
git clone https://git.drupal.org/project/anti_duplicates.git
git clone https://git.drupal.org/project/authbucket.git
git clone https://git.drupal.org/project/barrio.git
git clone https://git.drupal.org/project/base.git
git clone https://git.drupal.org/project/bear.git
git clone https://git.drupal.org/project/biolog.git
git clone https://git.drupal.org/project/brainstorm_profile.git
git clone https://git.drupal.org/project/bricky.git
git clone https://git.drupal.org/project/cabinetry.git
git clone https://git.drupal.org/project/cforge.git
git clone https://git.drupal.org/project/cms.git
git clone https://git.drupal.org/project/community_exchange.git
git clone https://git.drupal.org/project/concedra.git
git clone https://git.drupal.org/project/config_installer.git
git clone https://git.drupal.org/project/contacts_kickstart.git
git clone https://git.drupal.org/project/crux.git
git clone https://git.drupal.org/project/cucumber.git
git clone https://git.drupal.org/project/degov.git
git clone https://git.drupal.org/project/demo_umami_subprofile.git
git clone https://git.drupal.org/project/devmaster.git
git clone https://git.drupal.org/project/df.git
git clone https://git.drupal.org/project/diad_distro.git
git clone https://git.drupal.org/project/drucloudaws.git
git clone https://git.drupal.org/project/drupal_consul.git
git clone https://git.drupal.org/project/drupal_origins.git
git clone https://git.drupal.org/project/drupalcamp.git
git clone https://git.drupal.org/project/druponent.git
git clone https://git.drupal.org/project/druppio_small_business_distribution.git
git clone https://git.drupal.org/project/drustack.git
git clone https://git.drupal.org/project/drutopia.git
git clone https://git.drupal.org/project/ee.git
git clone https://git.drupal.org/project/express.git
git clone https://git.drupal.org/project/fancy_kickstart.git
git clone https://git.drupal.org/project/farm.git
git clone https://git.drupal.org/project/file_entity_browser_ui_testing.git
git clone https://git.drupal.org/project/govcms8.git
git clone https://git.drupal.org/project/guardr.git
git clone https://git.drupal.org/project/hammersmith.git
git clone https://git.drupal.org/project/headless_ninja.git
git clone https://git.drupal.org/project/hiphopdrop.git
git clone https://git.drupal.org/project/hunter.git
git clone https://git.drupal.org/project/hunter_shop.git
git clone https://git.drupal.org/project/hyperdrupal.git
git clone https://git.drupal.org/project/invoicer.git
git clone https://git.drupal.org/project/jain_deepak/2732165.git
git clone https://git.drupal.org/project/jmeip.git
git clone https://git.drupal.org/project/law_firm.git
git clone https://git.drupal.org/project/leadgen.git
git clone https://git.drupal.org/project/lightning.git
git clone https://git.drupal.org/project/lissa_kickstart.git
git clone https://git.drupal.org/project/mandatory.git
git clone https://git.drupal.org/project/markaspot.git
git clone https://git.drupal.org/project/media_dev.git
git clone https://git.drupal.org/project/minimis.git
git clone https://git.drupal.org/project/multilingual_demo.git
git clone https://git.drupal.org/project/multipurpose_corporate_profile.git
git clone https://git.drupal.org/project/newspublish.git
git clone https://git.drupal.org/project/niobi.git
git clone https://git.drupal.org/project/nodestream.git
git clone https://git.drupal.org/project/octane.git
git clone https://git.drupal.org/project/omega_profile.git
git clone https://git.drupal.org/project/open_door.git
git clone https://git.drupal.org/project/openchurch.git
git clone https://git.drupal.org/project/opencrm_kickstart.git
git clone https://git.drupal.org/project/openedu.git
git clone https://git.drupal.org/project/openfed.git
git clone https://git.drupal.org/project/openhotel.git
git clone https://git.drupal.org/project/openlms.git
git clone https://git.drupal.org/project/openlucius.git
git clone https://git.drupal.org/project/openrestaurant.git
git clone https://git.drupal.org/project/opensaas.git
git clone https://git.drupal.org/project/openy.git
git clone https://git.drupal.org/project/pankm.git
git clone https://git.drupal.org/project/panopoly.git
git clone https://git.drupal.org/project/phpedu_profile.git
git clone https://git.drupal.org/project/presto.git
git clone https://git.drupal.org/project/project_kickstart.git
git clone https://git.drupal.org/project/promokit.git
git clone https://git.drupal.org/project/purencool.git
git clone https://git.drupal.org/project/quadstat.git
git clone https://git.drupal.org/project/quick_start.git
git clone https://git.drupal.org/project/razoreye_biz.git
git clone https://git.drupal.org/project/redacto.git
git clone https://git.drupal.org/project/sector.git
git clone https://git.drupal.org/project/seeds.git
git clone https://git.drupal.org/project/seo_starter_kit.git
git clone https://git.drupal.org/project/simplytest.git
git clone https://git.drupal.org/project/social.git
git clone https://git.drupal.org/project/spark.git
git clone https://git.drupal.org/project/splashawards.git
git clone https://git.drupal.org/project/starter.git
git clone https://git.drupal.org/project/tea.git
git clone https://git.drupal.org/project/tedxname.git
git clone https://git.drupal.org/project/thaigov.git
git clone https://git.drupal.org/project/thunder.git
git clone https://git.drupal.org/project/twelvestepintergroup.git
git clone https://git.drupal.org/project/university.git
git clone https://git.drupal.org/project/varbase.git
git clone https://git.drupal.org/project/vardoc.git
git clone https://git.drupal.org/project/vdd.git
git clone https://git.drupal.org/project/vdo.git
git clone https://git.drupal.org/project/vimeo_field_uploader.git
git clone https://git.drupal.org/project/vrupal.git
git clone https://git.drupal.org/project/webship.git
git clone https://git.drupal.org/project/wxt.git
git clone https://git.drupal.org/project/zircon_profile.git